// Generated by scripts/geo-data.mts. Do not edit by hand.
import type { MapId } from "../maps.ts";

/**
 * Each map's size in km, corner to corner, which sets how fast points fall
 * off with distance. The world uses GeoGuessr's own figure.
 */
export const MAP_SCALES: Record<MapId, number> = {
  "world": 14916.862,
  "europe": 7139,
  "americas": 14916.862,
  "asia": 12906.7,
  "africa": 11006.7,
  "oceania": 10269,
  "ireland": 497.3,
  "uk": 1281.4,
  "usa": 8232.2,
  "japan": 3097.1,
  "france": 1502.3
};

/** South, west, north and east edges of where each map's rounds can be, for framing the guess map. */
export const MAP_BOUNDS: Record<MapId, [number, number, number, number]> = {"world":[-60,-180,78,180],"europe":[27.81,-31.18,70.95,59.97],"americas":[-54.81,-166.53,71.29,-32.41],"asia":[-10.42,25.91,73.51,188.3],"africa":[-34.67,-17.48,37.27,55.8],"oceania":[-46.6,113.53,15.21,190.49],"ireland":[51.55,-10.27,55.25,-6.05],"uk":[49.93,-7.64,60.15,1.75],"usa":[19.73,-166.53,71.29,-68.02],"japan":[24.34,123,45.41,145.57],"france":[41.59,-4.62,51.03,9.46]};
