/**
 * The twenty buildings, with Cookie Clicker's own prices and base production,
 * so the pacing is the one people already know. Everything else about them is
 * this game's own.
 */

export interface Building {
  id: string;
  name: string;
  /** Lowercase, for the middle of a sentence. */
  single: string;
  plural: string;
  icon: string;
  /** What the first one costs. Each one after costs 15% more than the last. */
  price: number;
  /** Cookies per second from one of them, before any upgrades. */
  cps: number;
  /** What its tiered upgrades improve, as a plural noun. */
  tool: string;
  desc: string;
}

export const BUILDINGS: readonly Building[] = [
  {
    id: "cursor",
    name: "Cursor",
    single: "cursor",
    plural: "cursors",
    icon: "👆",
    price: 15,
    cps: 0.1,
    tool: "",
    desc: "Clicks the cookie for you, every ten seconds or so.",
  },
  {
    id: "grandma",
    name: "Grandma",
    single: "grandma",
    plural: "grandmas",
    icon: "👵",
    price: 100,
    cps: 1,
    tool: "rolling pins",
    desc: "A kind grandma with a batch always on the go.",
  },
  {
    id: "farm",
    name: "Farm",
    single: "farm",
    plural: "farms",
    icon: "🌾",
    price: 1_100,
    cps: 8,
    tool: "watering cans",
    desc: "Row upon row of cookie crops.",
  },
  {
    id: "mine",
    name: "Mine",
    single: "mine",
    plural: "mines",
    icon: "⛏️",
    price: 12_000,
    cps: 47,
    tool: "pickaxes",
    desc: "Tunnels down to the seams of chocolate chips.",
  },
  {
    id: "factory",
    name: "Factory",
    single: "factory",
    plural: "factories",
    icon: "🏭",
    price: 130_000,
    cps: 260,
    tool: "conveyor belts",
    desc: "Turns out cookies by the conveyor load.",
  },
  {
    id: "bank",
    name: "Bank",
    single: "bank",
    plural: "banks",
    icon: "🏦",
    price: 1_400_000,
    cps: 1_400,
    tool: "vaults",
    desc: "Cookies earn interest, and the interest is paid in cookies.",
  },
  {
    id: "temple",
    name: "Temple",
    single: "temple",
    plural: "temples",
    icon: "🏛️",
    price: 20_000_000,
    cps: 7_800,
    tool: "idols",
    desc: "Full of old, mysterious and very edible relics.",
  },
  {
    id: "wizard",
    name: "Wizard tower",
    single: "wizard tower",
    plural: "wizard towers",
    icon: "🧙",
    price: 330_000_000,
    cps: 44_000,
    tool: "wands",
    desc: "Summons cookies with a word and a wave.",
  },
  {
    id: "shipment",
    name: "Shipment",
    single: "shipment",
    plural: "shipments",
    icon: "🚀",
    price: 5_100_000_000,
    cps: 260_000,
    tool: "cargo pods",
    desc: "Brings fresh cookies in from the cookie planet.",
  },
  {
    id: "alchemy",
    name: "Alchemy lab",
    single: "alchemy lab",
    plural: "alchemy labs",
    icon: "⚗️",
    price: 75_000_000_000,
    cps: 1_600_000,
    tool: "crucibles",
    desc: "Turns gold into cookies, which is finally the right way round.",
  },
  {
    id: "portal",
    name: "Portal",
    single: "portal",
    plural: "portals",
    icon: "🌀",
    price: 1_000_000_000_000,
    cps: 10_000_000,
    tool: "keystones",
    desc: "Opens a door to a dimension made of dough.",
  },
  {
    id: "timemachine",
    name: "Time machine",
    single: "time machine",
    plural: "time machines",
    icon: "⏳",
    price: 14_000_000_000_000,
    cps: 65_000_000,
    tool: "hourglasses",
    desc: "Fetches cookies from before anyone ate them.",
  },
  {
    id: "antimatter",
    name: "Antimatter condenser",
    single: "antimatter condenser",
    plural: "antimatter condensers",
    icon: "⚛️",
    price: 170_000_000_000_000,
    cps: 430_000_000,
    tool: "coils",
    desc: "Squeezes the antimatter out of the universe and bakes with it.",
  },
  {
    id: "prism",
    name: "Prism",
    single: "prism",
    plural: "prisms",
    icon: "🌈",
    price: 2_100_000_000_000_000,
    cps: 2_900_000_000,
    tool: "lenses",
    desc: "Turns light into cookies. Light was mostly crumbs all along.",
  },
  {
    id: "chancemaker",
    name: "Chancemaker",
    single: "chancemaker",
    plural: "chancemakers",
    icon: "🍀",
    price: 26_000_000_000_000_000,
    cps: 21_000_000_000,
    tool: "dice",
    desc: "Makes cookies out of thin air, if you're lucky. You're lucky.",
  },
  {
    id: "fractal",
    name: "Fractal engine",
    single: "fractal engine",
    plural: "fractal engines",
    icon: "❄️",
    price: 310_000_000_000_000_000,
    cps: 150_000_000_000,
    tool: "spirals",
    desc: "Every cookie it makes is made of smaller cookies.",
  },
  {
    id: "console",
    name: "Javascript console",
    single: "javascript console",
    plural: "javascript consoles",
    icon: "💻",
    price: 71_000_000_000_000_000_000,
    cps: 1_100_000_000_000,
    tool: "keyboards",
    desc: "Types cookies into existence, one line at a time.",
  },
  {
    id: "idleverse",
    name: "Idleverse",
    single: "idleverse",
    plural: "idleverses",
    icon: "🌌",
    price: 12_000_000_000_000_000_000_000,
    cps: 8_300_000_000_000,
    tool: "anchors",
    desc: "A whole universe of idle bakers, borrowed for a while.",
  },
  {
    id: "cortex",
    name: "Cortex baker",
    single: "cortex baker",
    plural: "cortex bakers",
    icon: "🧠",
    price: 1_900_000_000_000_000_000_000_000,
    cps: 64_000_000_000_000,
    tool: "thinking caps",
    desc: "A brain the size of a planet, dreaming about cookies.",
  },
  {
    id: "you",
    name: "You",
    single: "copy of you",
    plural: "copies of you",
    icon: "👤",
    price: 540_000_000_000_000_000_000_000_000,
    cps: 510_000_000_000_000,
    tool: "mirrors",
    desc: "Another you. You are, after all, very good at this.",
  },
];

export const CURSOR = 0;
export const GRANDMA = 1;
